# Generated by Django 4.1.4 on 2022-12-23 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagosv1',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expiredpayments',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_payments_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
